### All are ML algorithym i will build on the top of this dataset. after that i will select best one of them algorithm.

In [1]:
# All are necessary libraries and classes are importing

import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
import lazypredict
from lazypredict.Supervised import LazyClassifier
from lazypredict.Supervised import LazyRegressor
import joblib
import pickle
import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_rows',None)

In [3]:
scaled_data = pd.read_csv('Data/final_scaled_data.csv')
scaled_data.head()

,age,sex,TSH,TSH measured,pregnant,TT4 measured,T4U measured,FTI,FTI measured,I131 treatment,psych,on thyroxine,sick,labels,continues_target
0,0.27,0,0.01,1,0,1,0,0.28,0,0,0,0,0,2,1442.00
1,0.55,1,0.00,1,0,1,1,0.30,1,0,0,0,0,2,2965.00
2,0.84,0,0.00,1,0,1,0,0.28,0,0,0,1,0,2,806.00
3,0.84,0,0.00,1,0,1,1,0.17,1,0,0,0,0,2,2807.00
4,0.21,0,0.00,1,0,1,1,0.35,1,0,0,1,0,2,3434.00

In [4]:
without_scaled_data = pd.read_csv('Data/final_without_scaled_data.csv')
without_scaled_data.head()

,age,sex,TSH,TSH measured,pregnant,TT4 measured,T4U measured,FTI,FTI measured,I131 treatment,psych,on thyroxine,sick,labels,continues_target
0,23.00,0,4.10,1,0,1,0,110.47,0,0,0,0,0,2,1442.00
1,46.00,1,0.98,1,0,1,1,120.00,1,0,0,0,0,2,2965.00
2,70.00,0,0.16,1,0,1,0,110.47,0,0,0,1,0,2,806.00
3,70.00,0,0.72,1,0,1,1,70.00,1,0,0,0,0,2,2807.00
4,18.00,0,0.03,1,0,1,1,141.00,1,0,0,1,0,2,3434.00

In [5]:
df = without_scaled_data[without_scaled_data['age']<84]
df.head()

,age,sex,TSH,TSH measured,pregnant,TT4 measured,T4U measured,FTI,FTI measured,I131 treatment,psych,on thyroxine,sick,labels,continues_target
0,23.00,0,4.10,1,0,1,0,110.47,0,0,0,0,0,2,1442.00
1,46.00,1,0.98,1,0,1,1,120.00,1,0,0,0,0,2,2965.00
2,70.00,0,0.16,1,0,1,0,110.47,0,0,0,1,0,2,806.00
3,70.00,0,0.72,1,0,1,1,70.00,1,0,0,0,0,2,2807.00
4,18.00,0,0.03,1,0,1,1,141.00,1,0,0,1,0,2,3434.00

In [6]:
df[df['labels']==1]

,age,sex,TSH,TSH measured,pregnant,TT4 measured,T4U measured,FTI,FTI measured,I131 treatment,psych,on thyroxine,sick,labels,continues_target
26,25.00,0,0.30,1,0,1,0,110.47,0,0,0,0,0,1,185.00
54,77.00,1,2.00,1,0,1,1,111.00,1,0,0,0,0,1,942.00
85,31.00,0,1.30,1,0,1,1,121.00,1,0,0,0,0,1,3656.00
94,26.00,0,2.00,1,0,1,1,84.00,1,0,0,0,0,1,343.00
119,23.00,0,0.02,1,0,1,1,83.00,1,0,0,0,0,1,2668.00
125,30.00,0,2.70,1,1,1,1,87.00,1,0,0,0,0,1,3642.00
129,29.00,0,1.60,1,0,1,1,99.00,1,0,0,0,0,1,3035.00
133,80.00,1,1.30,1,0,1,1,134.00,1,0,0,0,0,1,2394.00
196,83.00,1,1.60,1,0,1,1,92.00,1,0,0,0,0,1,3207.00
198,32.00,0,0.03,1,1,1,1,104.00,1,0,0,1,0,1,855.00
212,34.00,0,26.00,1,0,1,1,88.00,1,0,0,1,0,1,2318.00
233,47.00,0,0.01,1,0,1,1,117.00,1,0,0,0,0,1,2026.00
234,53.00,0,0.05,1,0,1,1,155.00,1,0,0,0,0,1,3305.00
248,25.00,0,1.60,1,0,1,1,102.00,1,0,0,0,0,1,1183.00
270,21.00,0,0.40,1,0,1,1,140.00,1,0,0,0,0,1,338.00
299,28.00,0,0.80,1,0,1,1,100.00,1,0,0,0,0,1,2278.00
337,45.00,0,0.08,1,0,1,1,214.00,1,0,0,0,0,1,3303.00
365,32.00,0,0.50,1,1,1,1,92.00,1,0,1,0,0,1,197.00
396,20.00,0,0.90,1,0,1,1,93.00,1,0,0,0,0,1,145.00
422,27.00,0,5.09,0,0,1,1,106.00,1,0,0,0,0,1,832.00
485,29.00,0,0.10,1,1,1,1,80.00,1,0,0,0,0,1,193.00
518,42.00,0,0.04,1,0,1,1,100.00,1,0,0,0,0,1,1237.00
529,26.00,0,0.30,1,1,1,1,76.00,1,0,0,0,0,1,447.00
549,23.00,0,7.20,1,0,1,1,92.00,1,0,0,0,0,1,1214.00
561,65.00,0,1.30,1,0,1,1,137.00,1,1,0,0,0,1,2597.00
598,34.00,0,0.20,1,1,1,1,131.00,1,0,0,0,0,1,684.00
630,28.00,0,1.20,1,0,1,1,115.00,1,0,0,0,0,1,3240.00
646,34.00,0,19.00,1,0,1,1,125.00,1,0,0,0,0,1,3570.00
668,51.00,0,0.04,1,0,1,1,148.00,1,0,0,0,0,1,3298.00
690,29.00,0,1.10,1,0,1,1,93.00,1,0,0,0,0,1,3581.00
732,72.00,0,4.00,1,0,1,1,122.00,1,0,0,0,0,1,3682.00
739,28.00,0,0.90,1,0,1,1,100.00,1,0,0,0,0,1,2276.00
777,34.00,0,0.06,1,1,1,1,94.00,1,0,0,0,0,1,2911.00
782,34.00,0,0.25,1,0,1,1,133.00,1,0,0,1,0,1,1915.00
787,36.00,0,0.04,1,1,1,1,90.00,1,0,0,0,0,1,780.00
794,20.00,0,2.40,1,0,1,0,110.47,0,0,0,0,0,1,2154.00
800,22.00,0,5.60,1,0,1,1,101.00,1,0,0,0,0,1,2189.00
804,71.00,0,0.16,1,0,1,1,123.00,1,0,0,0,1,1,2599.00
824,21.00,0,3.10,1,0,1,1,201.00,1,0,0,0,0,1,3489.00
839,23.00,0,2.50,1,0,1,1,108.00,1,0,0,0,0,1,2862.00
852,73.00,0,0.42,1,0,1,1,79.00,1,0,0,0,0,1,3617.00
884,36.00,0,0.03,1,1,1,1,119.00,1,0,0,1,0,1,1180.00
889,36.00,0,7.50,1,0,1,1,84.00,1,0,0,0,0,1,528.00
962,46.00,1,2.10,1,0,1,1,105.00,1,0,0,0,0,1,2488.00
971,36.00,0,0.20,1,0,1,1,107.00,1,0,0,0,0,1,619.00
975,60.00,0,3.80,1,0,1,1,58.00,1,0,0,0,0,1,594.00
993,34.00,0,0.04,1,1,1,1,91.00,1,0,0,0,0,1,798.00
994,34.00,0,0.01,1,1,1,1,111.00,1,0,0,0,0,1,2522.00
1021,48.00,1,3.50,1,0,1,1,123.00,1,0,0,0,0,1,3040.00
1036,53.00,0,2.40,1,0,1,1,103.00,1,0,0,0,1,1,3366.00
1077,26.00,0,1.20,1,1,1,1,106.00,1,0,0,0,0,1,579.00
1143,34.00,0,0.02,1,1,1,1,104.00,1,0,0,0,0,1,1253.00
1145,59.00,0,0.65,1,0,1,1,96.00,1,0,0,0,0,1,2121.00
1169,38.00,0,1.50,1,0,1,1,83.00,1,0,0,0,0,1,1018.00
1174,15.00,0,3.40,1,0,1,1,86.00,1,0,0,0,0,1,1148.00
1188,71.00,0,0.09,1,0,1,1,140.00,1,0,0,0,0,1,2398.00
1214,4.00,1,0.07,1,0,1,1,232.00,1,0,0,0,0,1,3078.00
1218,38.00,0,0.23,1,0,1,1,186.00,1,0,0,0,0,1,830.00
1235,59.00,0,1.80,1,0,1,1,94.00,1,0,0,0,0,1,2527.00
1236,39.00,0,2.20,1,0,1,1,100.00,1,0,0,0,0,1,2657.00
1237,76.00,0,0.10,1,0,1,1,97.00,1,0,0,0,0,1,10.00
1241,34.00,0,0.02,1,1,1,1,119.00,1,0,0,0,0,1,1334.00
1308,56.00,0,5.20,1,0,1,1,107.00,1,0,0,0,0,1,876.00
1364,19.00,0,3.70,1,0,1,1,80.00,1,0,0,0,0,1,2404.00
1388,30.00,0,0.60,1,0,1,1,96.00,1,0,0,0,0,1,659.00
1423,31.00,0,0.10,1,0,1,1,132.00,1,0,0,0,0,1,36.00
1425,27.00,0,1.50,1,0,1,1,133.00,1,0,0,0,0,1,2806.00
1439,34.00,0,0.01,1,1,1,1,111.00,1,0,0,0,0,1,1523.00
1444,59.00,0,0.60,1,0,1,1,97.00,1,0,0,0,0,1,755.00
1476,34.00,0,8.30,1,1,1,1,96.00,1,0,0,1,0,1,1599.00
1585,34.00,0,2.40,1,1,1,1,80.00,1,0,0,0,0,1,3177.00
1632,34.00,0,0.10,1,0,1,1,147.00,1,0,0,1,0,1,192.00
1640,38.00,0,0.15,1,0,1,1,89.00,1,0,0,0,0,1,1866.00
1642,28.00,0,9.00,1,0,1,1,106.00,1,0,0,0,0,1,1736.00
1654,32.00,0,0.30,1,1,1,1,89.00,1,0,0,1,0,1,243.00
1673,27.00,0,0.02,1,0,1,1,78.00,1,0,0,0,0,1,1394.00
1690,54.00,0,5.09,0,0,1,1,75.00,1,0,0,0,0,1,249.00
1720,29.00,0,0.15,1,1,1,1,82.00,1,0,0,0,0,1,1853.00
1750,42.00,0,0.02,1,1,1,1,128.00,1,0,0,0,0,1,2176.00
1756,23.00,0,3.60,1,0,1,1,80.00,1,0,0,0,0,1,1585.00
1762,32.00,1,5.09,0,0,1,1,104.00,1,0,0,0,0,1,1438.00
1763,30.00,0,0.71,1,1,1,1,90.00,1,0,0,0,0,1,2468.00
1788,74.00,1,1.40,1,0,1,1,79.00,1,0,0,0,0,1,3401.00
1798,32.00,0,0.05,1,0,1,1,129.00,1,0,0,0,0,1,520.00
1829,18.00,0,0.90,1,0,1,1,108.00,1,0,0,0,0,1,1799.00
1925,34.00,0,0.05,1,1,1,1,110.00,1,0,0,0,0,1,517.00
1951,36.00,0,8.60,1,0,1,1,79.00,1,0,0,0,0,1,553.00
1959,24.00,0,0.85,1,0,1,1,97.00,1,0,0,0,0,1,1539.00
1978,64.00,0,0.05,1,0,1,1,140.00,1,0,0,0,0,1,519.00
1994,23.00,0,2.90,1,0,1,1,130.00,1,0,0,0,0,1,945.00
2001,36.00,0,1.30,1,0,1,1,102.00,1,0,0,0,0,1,910.00
2002,48.00,0,2.00,1,0,1,1,109.00,1,0,0,0,0,1,1470.00
2024,19.00,0,3.20,1,0,1,1,91.00,1,0,0,0,0,1,1613.00
2027,25.00,0,0.30,1,0,1,1,111.00,1,0,0,0,0,1,400.00
2069,32.00,1,1.00,1,0,1,1,130.00,1,0,0,0,0,1,1716.00
2112,61.00,1,7.90,1,0,1,1,114.00,1,0,0,0,0,1,1633.00
2160,35.00,0,3.00,1,0,1,1,79.00,1,0,0,0,0,1,1733.00
2169,27.00,0,5.09,0,1,1,1,100.00,1,0,0,0,0,1,2915.00
2185,26.00,0,1.40,1,0,1,1,84.00,1,0,0,0,0,1,538.00
2222,75.00,0,0.46,1,1,1,1,91.00,1,0,0,0,0,1,1562.00
2260,74.00,0,5.09,0,0,1,1,148.00,1,0,0,0,0,1,2092.00
2280,48.00,0,0.96,1,0,1,1,96.00,1,0,0,0,0,1,3621.00
2281,75.00,0,6.70,1,0,1,1,132.00,1,0,0,0,0,1,3316.00
2365,32.00,0,0.05,1,1,1,1,165.00,1,0,0,1,0,1,3263.00
2376,63.00,0,0.43,1,0,1,1,83.00,1,0,0,0,0,1,2384.00
2389,34.00,0,4.10,1,0,1,1,98.00,1,0,0,0,0,1,2465.00
2429,24.00,0,0.25,1,0,1,1,108.00,1,0,0,0,0,1,2.00
2473,63.00,0,5.09,0,0,1,1,118.00,1,0,0,0,0,1,2830.00
2491,47.00,0,0.63,1,0,1,1,134.00,1,0,0,0,0,1,1675.00
2515,70.00,0,1.10,1,0,1,1,134.00,1,0,0,0,0,1,2287.00
2520,29.00,0,0.15,1,0,1,1,100.00,1,0,0,0,0,1,882.00
2538,29.00,0,0.80,1,0,1,1,114.00,1,0,0,0,0,1,313.00
2610,42.00,0,0.01,1,1,1,1,121.00,1,0,0,0,0,1,1522.00
2616,59.00,0,1.10,1,0,1,1,155.00,1,0,0,0,0,1,2079.00
2657,20.00,0,0.70,1,0,1,1,100.00,1,0,0,0,0,1,2900.00
2674,30.00,0,1.20,1,0,1,1,98.00,1,0,0,0,0,1,1877.00
2709,44.00,0,1.90,1,0,1,1,119.00,1,0,0,0,0,1,2899.00
2720,70.00,0,2.10,1,0,1,1,139.00,1,0,0,0,0,1,581.00
2721,19.00,0,4.00,1,0,1,1,119.00,1,0,0,0,0,1,2346.00
2736,29.00,0,0.62,1,1,1,1,112.00,1,0,0,0,0,1,1481.00
2746,14.00,0,1.90,1,0,1,1,116.00,1,0,0,0,0,1,3418.00
2755,75.00,0,0.20,1,0,1,1,78.00,1,0,0,0,0,1,1756.00
2758,72.00,0,3.70,1,0,1,1,60.00,1,0,0,0,0,1,1445.00
2793,25.00,0,1.90,1,0,1,1,137.00,1,0,0,0,0,1,2245.00
2813,54.00,0,0.14,1,0,1,0,110.47,0,0,0,0,0,1,3076.00
2823,51.00,0,5.80,1,0,1,1,113.00,1,0,0,0,0,1,3458.00
2876,59.00,0,1.20,1,0,1,1,86.00,1,0,0,0,0,1,3016.00
2909,46.00,1,4.80,1,0,1,1,104.00,1,0,1,0,0,1,1203.00
2968,23.00,0,4.60,1,0,1,1,92.00,1,0,0,0,0,1,3379.00
2988,34.00,0,0.03,1,1,1,1,81.00,1,0,0,0,0,1,1651.00
2999,54.00,0,3.10,1,0,1,1,103.00,1,0,0,0,0,1,1647.00
3006,27.00,0,0.94,1,0,1,1,100.00,1,0,0,0,0,1,2912.00
3042,58.00,0,0.30,1,0,1,1,108.00,1,0,0,0,0,1,1999.00
3075,60.00,0,0.77,1,0,1,1,119.00,1,0,0,0,0,1,1305.00
3086,50.00,0,0.60,1,0,1,1,63.00,1,0,0,0,0,1,3036.00
3116,67.00,0,0.84,1,0,1,1,122.00,1,0,0,0,0,1,2701.00
3128,34.00,0,0.04,1,0,1,1,97.00,1,0,0,0,0,1,2236.00
3273,59.00,0,0.82,1,0,1,1,126.00,1,0,0,0,0,1,2032.00
3288,75.00,0,0.25,1,0,1,1,134.00,1,1,0,0,0,1,473.00
3313,12.00,0,2.40,1,0,1,1,138.00,1,0,0,0,1,1,3319.00
3391,36.00,0,2.40,1,0,1,1,87.00,1,0,0,0,0,1,1209.00
3424,32.00,0,4.10,1,0,1,1,78.00,1,0,0,0,0,1,667.00
3447,30.00,0,0.76,1,0,1,1,84.00,1,0,0,0,0,1,3309.00
3511,40.00,0,0.15,1,1,1,1,142.00,1,0,0,0,0,1,436.00
3603,38.00,0,0.50,1,0,1,1,94.00,1,0,0,0,0,1,646.00
3622,34.00,0,5.09,0,0,1,1,75.00,1,0,0,1,0,1,1801.00
3669,30.00,0,1.10,1,1,1,1,96.00,1,0,0,0,0,1,1540.00
3689,27.00,0,2.20,1,1,1,1,78.00,1,0,0,0,0,1,1302.00
3708,26.00,0,0.20,1,1,1,1,96.00,1,0,0,1,0,1,1769.00

In [7]:
scaled_data.shape

(3682, 15)

In [8]:
df.shape

(3682, 15)

## Model Building with Lazypredict on scaling data,
    lazypredict is a python which is used for as like the survey. to get 
    general overview of  our model building in a fews steps. it will train all the 
    models on the specific dataset. and gives the accuracy,precision,recall as an output

In [9]:
scaled_data.head()

,age,sex,TSH,TSH measured,pregnant,TT4 measured,T4U measured,FTI,FTI measured,I131 treatment,psych,on thyroxine,sick,labels,continues_target
0,0.27,0,0.01,1,0,1,0,0.28,0,0,0,0,0,2,1442.00
1,0.55,1,0.00,1,0,1,1,0.30,1,0,0,0,0,2,2965.00
2,0.84,0,0.00,1,0,1,0,0.28,0,0,0,1,0,2,806.00
3,0.84,0,0.00,1,0,1,1,0.17,1,0,0,0,0,2,2807.00
4,0.21,0,0.00,1,0,1,1,0.35,1,0,0,1,0,2,3434.00

In [10]:
x = scaled_data.drop(['labels','continues_target'],axis = 1)
y = scaled_data['labels']

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
lazyclasifier = LazyClassifier(verbose=0,ignore_warnings=True,custom_metric=accuracy_score)

In [13]:
models , predictions = lazyclasifier.fit(x_train,x_test,y_train,y_test)

 93%|█████████▎| 27/29 [00:04<00:00,  7.13it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001349 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 513
[LightGBM] [Info] Number of data points in the train set: 2945, number of used features: 13
[LightGBM] [Info] Start training from score -5.502957
[LightGBM] [Info] Start training from score -3.105062
[LightGBM] [Info] Start training from score -0.050132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

100%|██████████| 29/29 [00:05<00:00,  5.09it/s]

### result of models by lazypredict

In [14]:
models1 = pd.DataFrame(models)
models1

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,accuracy_score,Time Taken
Model,,,,,,
NearestCentroid,0.42,0.53,None,0.59,0.42,0.02
GaussianNB,0.18,0.45,None,0.30,0.18,0.02
BaggingClassifier,0.98,0.41,None,0.97,0.98,0.17
DecisionTreeClassifier,0.94,0.40,None,0.95,0.94,0.03
PassiveAggressiveClassifier,0.88,0.40,None,0.92,0.88,0.04
SVC,0.98,0.39,None,0.97,0.98,0.31
SGDClassifier,0.98,0.39,None,0.97,0.98,0.04
RidgeClassifierCV,0.98,0.39,None,0.97,0.98,0.03
RidgeClassifier,0.98,0.39,None,0.97,0.98,0.06
LinearDiscriminantAnalysis,0.98,0.39,None,0.97,0.98,0.05
CalibratedClassifierCV,0.98,0.39,None,0.97,0.98,0.38
BernoulliNB,0.98,0.39,None,0.97,0.98,0.02
LinearSVC,0.98,0.39,None,0.97,0.98,0.55
Perceptron,0.98,0.39,None,0.97,0.98,0.02
ExtraTreeClassifier,0.95,0.38,None,0.95,0.95,0.02
LogisticRegression,0.98,0.37,None,0.97,0.98,0.11
RandomForestClassifier,0.98,0.37,None,0.97,0.98,0.59
AdaBoostClassifier,0.97,0.37,None,0.97,0.97,0.35
LabelSpreading,0.97,0.37,None,0.97,0.97,0.82
LGBMClassifier,0.97,0.37,None,0.97,0.97,0.70
ExtraTreesClassifier,0.97,0.37,None,0.96,0.97,0.46
QuadraticDiscriminantAnalysis,0.18,0.37,None,0.27,0.18,0.04
LabelPropagation,0.97,0.35,None,0.96,0.97,0.46
KNeighborsClassifier,0.97,0.35,None,0.96,0.97,0.10
XGBClassifier,0.97,0.35,None,0.96,0.97,0.23
DummyClassifier,0.98,0.33,None,0.96,0.98,0.02

### Lazypredict model on without scaling data

In [15]:
x = without_scaled_data.drop(['labels','continues_target'],axis = 1)
y = without_scaled_data['labels']

In [16]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
lazyclasifier2 = LazyClassifier(verbose=0,ignore_warnings=True,custom_metric=accuracy_score)

In [18]:
models2 , predictions2 = lazyclasifier2.fit(x_train,x_test,y_train,y_test)

100%|██████████| 29/29 [00:04<00:00,  6.63it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000125 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 519
[LightGBM] [Info] Number of data points in the train set: 3016, number of used features: 13
[LightGBM] [Info] Start training from score -5.613791
[LightGBM] [Info] Start training from score -3.191405
[LightGBM] [Info] Start training from score -0.045794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [19]:
pd.DataFrame(models2)

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,accuracy_score,Time Taken
Model,,,,,,
Perceptron,0.92,0.43,None,0.93,0.92,0.02
BaggingClassifier,0.95,0.39,None,0.95,0.95,0.10
KNeighborsClassifier,0.96,0.38,None,0.95,0.96,0.06
RandomForestClassifier,0.96,0.38,None,0.95,0.96,0.52
NearestCentroid,0.35,0.38,None,0.51,0.35,0.01
SVC,0.96,0.37,None,0.95,0.96,0.16
LinearSVC,0.96,0.37,None,0.95,0.96,0.59
BernoulliNB,0.96,0.37,None,0.95,0.96,0.01
CalibratedClassifierCV,0.96,0.37,None,0.95,0.96,0.20
RidgeClassifierCV,0.96,0.37,None,0.95,0.96,0.04
RidgeClassifier,0.96,0.37,None,0.95,0.96,0.02
LinearDiscriminantAnalysis,0.96,0.37,None,0.95,0.96,0.03
LogisticRegression,0.96,0.37,None,0.95,0.96,0.04
LabelPropagation,0.96,0.37,None,0.95,0.96,0.53
LabelSpreading,0.96,0.37,None,0.95,0.96,0.87
AdaBoostClassifier,0.96,0.37,None,0.95,0.96,0.31
ExtraTreesClassifier,0.96,0.37,None,0.95,0.96,0.37
XGBClassifier,0.95,0.37,None,0.95,0.95,0.15
LGBMClassifier,0.95,0.37,None,0.95,0.95,0.16
ExtraTreeClassifier,0.94,0.36,None,0.94,0.94,0.02
DecisionTreeClassifier,0.91,0.35,None,0.92,0.91,0.03
DummyClassifier,0.96,0.33,None,0.94,0.96,0.02
SGDClassifier,0.96,0.33,None,0.94,0.96,0.03
GaussianNB,0.17,0.33,None,0.29,0.17,0.02
QuadraticDiscriminantAnalysis,0.18,0.33,None,0.26,0.18,0.02
PassiveAggressiveClassifier,0.96,0.33,None,0.94,0.96,0.02

### top 5 models which are trained on this data

In [20]:
models1.sort_values(by = 'Balanced Accuracy',ascending=False)[0:5]

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,accuracy_score,Time Taken
Model,,,,,,
NearestCentroid,0.42,0.53,None,0.59,0.42,0.02
GaussianNB,0.18,0.45,None,0.30,0.18,0.02
BaggingClassifier,0.98,0.41,None,0.97,0.98,0.17
DecisionTreeClassifier,0.94,0.40,None,0.95,0.94,0.03
PassiveAggressiveClassifier,0.88,0.40,None,0.92,0.88,0.04

## Model Building with Hyperparameter turning on scaled data

In [21]:
model_and_parameter ={

"Logistic_Regression" :{
                        "model" : LogisticRegression(),
                        "param" : {'penalty':['l1', 'l2', 'elasticnet'],
                                    'solver' : ['newton-cg', 'lbfgs', 'liblinear']}
                       },

"Decision_Tree" :{
                        "model" : DecisionTreeClassifier(),
                        "param" : {'criterion' : ["gini", "entropy","log_loss"],
                                  'splitter' : ["best", "random"],
                                  'max_depth':range(4,16,1),
                                  'min_samples_leaf':range(2,8,1),
                                  'min_samples_split':range(2,8,1)}
                                  
                 },

"SVC" : {
                        "model" : SVC(),
                        "param" : {'C' :[1.0],
                                   'kernel' : ['linear', 'poly', 'rbf'],
                                   'gamma': ['scale','auto']}
                                  
       },

"KNeighborsClassifier" : {
                        "model" : KNeighborsClassifier(),
                        "param" : {'n_neighbors' : [3,5,7,9],
                                  'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
                                  'metric':['euclidian','minkowski']}
                                   
                        },

"GaussianNB" :  {
                    "model" : GaussianNB(),
                    "param" : {}
                 },


"RandomForestClassifier" :{
                    "model" : RandomForestClassifier(),
                    "param" : {'criterion' : ["gini", "entropy"],
                            'n_estimators' : [80,100,120,135,150],
                            'max_depth':range(4,16,1),
                            'min_samples_leaf':range(1,8,1),
                            'min_samples_split':range(2,8,1)
                              }
                      },

 "AdaBoostClassifier" :{
                    "model" : AdaBoostClassifier(),
                    "param" : {'n_estimators' : [10,50,100],
                                'learning_rate':[1.0,0.02,0.04,0.4],}
                      },

"GradientBoostingClassifier" :{
                    "model" : GradientBoostingClassifier(),
                    "param" : {'n_estimators' : [10,50,100],
                              'learning_rate':[1.0,0.02,0.04,0.4],
                              'criterion' : ['friedman_mse', 'squared_error', 'mse'], 
                              'min_samples_split':range(3,7,1),
                              'min_samples_leaf':range(1,7,1),
                              'max_depth':range(3,6,1)}
                      },

"XGBClassifier" :{
                    "model" : XGBClassifier(),
                    "param" : {}
}

}

### due to more computation power required ,i skipped some of them hyperparameters

In [22]:
model_and_parameter ={

"Logistic_Regression" :{
                        "model" : LogisticRegression(),
                        "param" : {'penalty':['l1', 'l2', 'elasticnet'],
                                    'solver' : ['newton-cg', 'lbfgs', 'liblinear']}
                       },

"Decision_Tree" :{
                        "model" : DecisionTreeClassifier(),
                        "param" : {'criterion' : ["gini", "entropy","log_loss"],
                                  'splitter' : ["best", "random"],
                                  'max_depth':range(4,16,1),
                                  'min_samples_leaf':range(2,8,1),
                                  'min_samples_split':range(2,8,1)}
                                  
                 },

"SVC" : {
                        "model" : SVC(),
                        "param" : {'C' :[1.0],
                                   'kernel' : ['linear', 'poly', 'rbf'],
                                   'gamma': ['scale','auto']}
                                  
       },

"KNeighborsClassifier" : {
                        "model" : KNeighborsClassifier(),
                        "param" : {'n_neighbors' : [3,5,7,9],
                                  'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
                                  'metric':['euclidian','minkowski']}
                                   
                        },

"GaussianNB" :  {
                    "model" : GaussianNB(),
                    "param" : {}
                 },


"RandomForestClassifier" :{
                    "model" : RandomForestClassifier(),
                    "param" : {'criterion' : ["gini", "entropy"],
                            'n_estimators' : [80,100,120,135,150]
                            
                              }
                      },

 "AdaBoostClassifier" :{
                    "model" : AdaBoostClassifier(),
                    "param" : {'n_estimators' : [10,50,100],
                                'learning_rate':[1.0,0.02,0.04,0.4],}
                      },

"GradientBoostingClassifier" :{
                    "model" : GradientBoostingClassifier(),
                    "param" : {'n_estimators' : [10,50,100],
                             }
                      },

"XGBClassifier" :{
                    "model" : XGBClassifier(),
                    "param" : {}
}

}

### Train test split on scaled data

In [23]:
scaled_data.head()

,age,sex,TSH,TSH measured,pregnant,TT4 measured,T4U measured,FTI,FTI measured,I131 treatment,psych,on thyroxine,sick,labels,continues_target
0,0.27,0,0.01,1,0,1,0,0.28,0,0,0,0,0,2,1442.00
1,0.55,1,0.00,1,0,1,1,0.30,1,0,0,0,0,2,2965.00
2,0.84,0,0.00,1,0,1,0,0.28,0,0,0,1,0,2,806.00
3,0.84,0,0.00,1,0,1,1,0.17,1,0,0,0,0,2,2807.00
4,0.21,0,0.00,1,0,1,1,0.35,1,0,0,1,0,2,3434.00

In [24]:
len(scaled_data.columns)

15

In [25]:
x = scaled_data.drop(['labels','continues_target'],axis = 1)
y = scaled_data['labels']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [26]:
x_train.shape

(2945, 13)

In [27]:
# By the gridsearchCV

Scores = []
for model_name ,model_param in model_and_parameter.items():
    gs = GridSearchCV(model_param['model'],model_param['param'],cv = 5,return_train_score=False)
    gs.fit(x_train,y_train)
    Scores.append({'Model': model_name,
                 'Best_Score' : gs.best_score_,
                 'Best_Parameter' : gs.best_params_})
    best_model_of_algo = gs.best_estimator_
    joblib.dump(best_model_of_algo,'models/ML_models/'+model_name+str(int(round(gs.best_score_,2)*100))+'.lb')     # to save the best model of algorithm

In [28]:
model_info = pd.DataFrame(Scores,columns=['Model','Best_Score','Best_Parameter'])
model_info.sort_values(by='Best_Score',ascending=False)

,Model,Best_Score,Best_Parameter
1,Decision_Tree,0.96,"{'criterion': 'gini', 'max_depth': 7, 'min_sam..."
2,SVC,0.95,"{'C': 1.0, 'gamma': 'scale', 'kernel': 'rbf'}"
5,RandomForestClassifier,0.95,"{'criterion': 'gini', 'n_estimators': 80}"
7,GradientBoostingClassifier,0.95,{'n_estimators': 10}
0,Logistic_Regression,0.95,"{'penalty': 'l1', 'solver': 'liblinear'}"
6,AdaBoostClassifier,0.95,"{'learning_rate': 1.0, 'n_estimators': 10}"
3,KNeighborsClassifier,0.95,"{'algorithm': 'auto', 'metric': 'minkowski', '..."
8,XGBClassifier,0.95,{}
4,GaussianNB,0.17,{}

In [29]:
model_info.sort_values(by='Best_Score',ascending=False).iloc[0,2]        # best parameter

{'criterion': 'gini',
 'max_depth': 7,
 'min_samples_leaf': 6,
 'min_samples_split': 5,
 'splitter': 'random'}

### Prediction & model evaluation

In [30]:
x_train.head()

,age,sex,TSH,TSH measured,pregnant,TT4 measured,T4U measured,FTI,FTI measured,I131 treatment,psych,on thyroxine,sick
1001,0.23,1,0.01,0,0,1,0,0.28,0,0,0,0,0
2493,0.84,1,0.00,1,0,1,1,0.26,1,0,0,0,0
1284,0.93,0,0.00,1,0,0,0,0.28,0,0,0,0,0
1151,0.51,0,0.00,1,0,1,1,0.46,1,0,0,1,0
3201,0.82,0,0.01,1,0,1,1,0.23,1,0,0,0,0

In [31]:
x_train.columns

Index(['age', 'sex', 'TSH', 'TSH measured', 'pregnant', 'TT4 measured',
       'T4U measured', 'FTI', 'FTI measured', 'I131 treatment', 'psych',
       'on thyroxine', 'sick'],
      dtype='object')

In [32]:
dtc = joblib.load('models\ML_models\KNeighborsClassifier95.lb')       #load the model
y_pred = dtc.predict(x_test)

In [33]:
y_pred

array([2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [34]:
accuracy_score(y_test,y_pred)           ## good accuracy on testing data

0.9755766621438263

In [35]:
confusion_matrix(y_test,y_pred)

array([[  0,   0,   1],
       [  0,   2,  15],
       [  0,   2, 717]], dtype=int64)

In [36]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      0.12      0.19        17
           2       0.98      1.00      0.99       719

    accuracy                           0.98       737
   macro avg       0.49      0.37      0.39       737
weighted avg       0.97      0.98      0.97       737

In [37]:
pd.DataFrame(y_pred)[0].value_counts()

0
2    733
1      4
Name: count, dtype: int64

In [38]:
pd.DataFrame(y_test)['labels'].value_counts()

labels
2    719
1     17
0      1
Name: count, dtype: int64

In [41]:
XGBC = joblib.load('models/ML_models/Decision_Tree96.lb')

In [42]:
pred2 = XGBC.predict(x_test)

In [43]:
accuracy_score(y_test,pred2)

0.9755766621438263

In [44]:
pd.DataFrame(y_test)['labels'].value_counts()

labels
2    719
1     17
0      1
Name: count, dtype: int64

In [45]:
pd.DataFrame(pred2)[0].value_counts()

0
2    733
1      4
Name: count, dtype: int64

In [46]:
lgr = joblib.load('models/ML_models/Logistic_Regression95.lb')

In [47]:
pred3 = lgr.predict(x_test)

In [48]:
accuracy_score(y_test,pred3)

0.9769335142469471

In [49]:
pd.DataFrame(y_test)['labels'].value_counts()

labels
2    719
1     17
0      1
Name: count, dtype: int64

In [50]:
pd.DataFrame(pred3)[0].value_counts()

0
2    734
1      3
Name: count, dtype: int64

### model  building completed,
this data was not in a linearFashion that,s why i got the maximum accuracy <br>
by the DecissionTreeClassifier. so i am selecting this model for the final model.